package com.mints.projectgammatwo.data

import android.content.Context
import android.content.SharedPreferences
import androidx.core.content.edit

/**
 * Quest data cached from the network: the API's filter lists, the per-filter sub-variants, and
 * when they were last refreshed. All of it is regenerated by the next fetch.
 *
 * Kept in its own file rather than in [FilterPreferences.QUEST_PREF_NAME], which holds the
 * user's quest filters, so that it can be excluded from backup (see res/xml/backup_rules.xml
 * and data_extraction_rules.xml). A cache restored onto a newer app version is stale by
 * definition — restoring one written before the t8 filter section existed is what crashed the
 * quest filter screen.
 */
object QuestCache {
    const val PREFS_NAME = "quest_cache"

    const val KEY_API_FILTERS = "quest_api_filters"
    const val KEY_SUB_VARIANTS = "quest_sub_variants"
    const val KEY_SUB_VARIANTS_TIMESTAMP = "quest_sub_variants_timestamp"
    const val KEY_FILTERS_LAST_REFRESHED = "filters_last_refreshed"

    private val STRING_KEYS = listOf(KEY_API_FILTERS, KEY_SUB_VARIANTS)
    private val LONG_KEYS = listOf(KEY_SUB_VARIANTS_TIMESTAMP, KEY_FILTERS_LAST_REFRESHED)

    @Volatile
    private var migrated = false

    fun prefs(context: Context): SharedPreferences {
        val cache = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        if (!migrated) migrateFromQuestFilters(context, cache)
        return cache
    }

    /**
     * Moves the cache out of the quest filters file, where earlier versions kept it, so that
     * existing installs keep their cache on upgrade and the old copy stops being backed up.
     */
    private fun migrateFromQuestFilters(context: Context, cache: SharedPreferences) {
        synchronized(this) {
            if (migrated) return
            val legacy = context.getSharedPreferences(
                FilterPreferences.QUEST_PREF_NAME, Context.MODE_PRIVATE
            )
            val present = (STRING_KEYS + LONG_KEYS).filter { legacy.contains(it) }
            if (present.isNotEmpty()) {
                cache.edit {
                    for (key in STRING_KEYS) {
                        if (key in present && !cache.contains(key)) {
                            putString(key, legacy.getString(key, null))
                        }
                    }
                    for (key in LONG_KEYS) {
                        if (key in present && !cache.contains(key)) {
                            putLong(key, legacy.getLong(key, 0L))
                        }
                    }
                }
                legacy.edit { present.forEach { remove(it) } }
            }
            migrated = true
        }
    }
}
